version: "3.7"

services:
  nifi:
    container_name: nifi-ignite-extensions_nifi
    image: apache/nifi:1.12.1
    entrypoint: [ "/opt/nifi/nifi-current/user/start.sh" ]
    networks:
      - nifi-ignite-extensions_network
    ports:
      - 3080:8080
    volumes:
      - ./nifi/user:/opt/nifi/nifi-current/user
      - ./ignite:/opt/nifi/nifi-current/ignite
    depends_on:
      - ignite

  ignite:
    image: apacheignite/ignite:${IGNITE_VERSION-2.10.0}
    container_name: nifi-ignite-extensions_ignite
    networks:
      - nifi-ignite-extensions_network
    ports:
      - 10800:10800
      - 11211:11211
      - 8080:8080
    volumes:
      - ./ignite:/user_config
    environment:
      - OPTION_LIBS=ignite-rest-http,ignite-indexing
      - CONFIG_URI=file:///user_config/ignite-config.xml

networks:
  nifi-ignite-extensions_network:
    attachable: true